In [1]:
from sklearn.datasets import load_iris
import pandas as pd

In [2]:
data = load_iris()
data = pd.DataFrame(data['data'], columns=['sepal length (cm)',
                    'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'])
data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [3]:
data = load_iris()
data.data.shape

(150, 4)

In [4]:
data.data[:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [8]:
from sklearn.feature_extraction import DictVectorizer

In [6]:
data = [{'courses_count': 4, 'GPA': 6.7}, {'courses_count': 4, 'GPA': 8.5},
        {'courses_count': 2, 'GPA': 8.1}, {'courses_count': 1, 'GPA': 7.2},
        {'courses_count': 1, 'GPA': 9.1}]

In [28]:
dv = DictVectorizer(sparse=False)
data_transformed = dv.fit_transform(data)
data_transformed[:3]
data_transformed[:2]

array([[6.7, 4. ],
       [8.5, 4. ],
       [8.1, 2. ]])

array([[6.7, 4. ],
       [8.5, 4. ]])

In [22]:
data_transformed
type(data_transformed)
data_transformed.dtype

array([[6.7, 4. ],
       [8.5, 4. ],
       [8.1, 2. ],
       [7.2, 1. ],
       [9.1, 1. ]])

numpy.ndarray

dtype('float64')

In [24]:
import numpy as np
from sklearn.impute import SimpleImputer

In [27]:
imp = SimpleImputer(missing_values=np.nan, strategy='median')
X = [[4, 1], [np.nan, 5], [8, 0]]
imp.fit_transform(X)

array([[4., 1.],
       [6., 5.],
       [8., 0.]])