In [8]:
import numpy as np
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_squared_error

from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In [2]:
# 1. Load the dataset
data = fetch_california_housing()
X, y = data.data, data.target

In [3]:
# 2. Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=1
)

# 3. Initialize models
models = {
    "Model 1 (Linear Regression)": LinearRegression(),
    "Model 2 (AdaBoost)": AdaBoostRegressor(random_state=1),
    "Model 3 (Decision Tree)": DecisionTreeRegressor(random_state=1)
}

results = {}

# 4. Train and Evaluate
for name, model in models.items():
  model.fit(X_train, y_train)
  predictions = model.predict(X_test)

  r2 = r2_score(y_test, predictions)
  rmse = np.sqrt(mean_squared_error(y_test, predictions))

  results[name] = {'R2': r2, 'RMSE': rmse}
  print(f"{name}: R2 = {r2:.4f}, RMSE = {rmse:.4f}")

# 5. Comparing results for the options
print("\n--- Summary for Comparison ---")
r2_1, r2_2, r2_3 = results["Model 1 (Linear Regression)"]['R2'], results["Model 2 (AdaBoost)"][
    'R2'], results["Model 3 (Decision Tree)"]['R2']
rmse_1, rmse_2, rmse_3 = results["Model 1 (Linear Regression)"]['RMSE'], results["Model 2 (AdaBoost)"][
    'RMSE'], results["Model 3 (Decision Tree)"]['RMSE']

LinearRegression()

Model 1 (Linear Regression): R2 = 0.5966, RMSE = 0.7274


AdaBoostRegressor(random_state=1)

Model 2 (AdaBoost): R2 = 0.3945, RMSE = 0.8912


DecisionTreeRegressor(random_state=1)

Model 3 (Decision Tree): R2 = 0.6179, RMSE = 0.7080

--- Summary for Comparison ---


In [5]:
# 1. Load the Iris Dataset
iris = load_iris()
X, y = iris.data, iris.target

# 2. Split the data: test_size = 0.33, random_state = 1
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=1
)

In [6]:
# 3. Train Logistic Regression model: random_state = 1
# Note: Increasing max_iter to ensure convergence for Iris
model = LogisticRegression(random_state=1, max_iter=200)
model.fit(X_train, y_train)

# 4. Make predictions
y_pred = model.predict(X_test)

LogisticRegression(max_iter=200, random_state=1)

In [7]:
# 5. Print Confusion Matrix and Classification Report
cm = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=iris.target_names)

print("Confusion Matrix:")
print(cm)
print("\nClassification Report:")
print(report)

# Calculate answers for the specific questions
misclassified = (y_test != y_pred).sum()
print(f"\nTotal misclassified samples: {misclassified}")

Confusion Matrix:
[[17  0  0]
 [ 0 18  1]
 [ 0  0 14]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        17
  versicolor       1.00      0.95      0.97        19
   virginica       0.93      1.00      0.97        14

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50


Total misclassified samples: 1


In [9]:
# 1. Load the train subset of 20newsgroups
newsgroups_train = fetch_20newsgroups(subset='train', return_X_y=True)
X_raw, y = newsgroups_train

# 2. Vectorize X using TfidfVectorizer (using default parameters as implied)
tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(X_raw)

# Question 4: Check the shape of the transformed data
print(f"Shape of the fitted and transformed data X: {X_tfidf.shape}")

Shape of the fitted and transformed data X: (11314, 130107)


In [10]:
# 3. Split the vectorized data: test_size = 0.3, random_state = 1
X_train, X_val, y_train, y_val = train_test_split(
    X_tfidf, y, test_size=0.3, random_state=1
)

# 4. Train a MultinomialNB model
clf = MultinomialNB()
clf.fit(X_train, y_train)

# Question 5: Compute the score (Accuracy) on the validation set
score = clf.score(X_val, y_val)
print(f"Score on the validation set: {score:.4f}")

MultinomialNB()

Score on the validation set: 0.8274
