In [2]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)

In [3]:
np.array([2, 3, 45])
np.zeros(4)
np.ones(4)

array([ 2,  3, 45])

array([0., 0., 0., 0.])

array([1., 1., 1., 1.])

In [4]:
matrix = [
    [1, 3, 4],
    [5, 6, 7]
]

print(matrix)
print(matrix[0])
print(matrix[0][0])

[[1, 3, 4], [5, 6, 7]]
[1, 3, 4]
1


In [5]:
for row in matrix:
  for elem in row:
    print(elem, end=',')

1,3,4,5,6,7,

In [6]:
for i in range(len(matrix)):
  for j in range(len(matrix[i])):
    print(f'{i}{j}', end=',')
  print()

00,01,02,
10,11,12,


In [7]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

matrix
matrix[0]
matrix[0][0]
matrix[0, 0]

array([[1, 2, 3],
       [4, 5, 6]])

array([1, 2, 3])

np.int64(1)

np.int64(1)

In [8]:
matrix.shape  # row, col
np.array([2, 3, 4, 5, 6]).shape

(2, 3)

(5,)

In [9]:
np.zeros(5)
np.zeros((2, 3))

array([0., 0., 0., 0., 0.])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
matrix = [
    [2, 3],
    [2, 3, 4]
]

matrix[0][1]
matrix[1][2]

3

4

In [11]:
matrix = np.array([
    [2, 3, 0],
    [2, 3, 4]
])

matrix.shape

(2, 3)

- Type of the elements stored in array
- Size of the stored elements in bytes
- Arrays are fixed width, every element uses same number of bytes

In [12]:
arr1 = np.array([1, 2, 3])
arr1.dtype, arr1.itemsize

arr2 = np.array(['apple', 'banana'])
arr2.dtype, arr2.itemsize

arr3 = np.array(['pineapple', 'banana'])
arr3.dtype, arr3.itemsize

arr4 = np.array([1, 'banana'])
arr4.dtype, arr4.itemsize

(dtype('int64'), 8)

(dtype('<U6'), 24)

(dtype('<U9'), 36)

(dtype('<U21'), 84)

In [13]:
np.eye(4)  # Identity matrix of 4 length

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [62]:
arr1 = np.array([1, 2, 3])
arr1.ndim
arr1.size
arr1.shape

arr2 = np.array([[1, 2, 3], [3, 4, 5]])
arr2.ndim
arr2.size
arr2.shape

arr3 = np.array([[[2], [4], [1]], [[5], [6], [8]]])
arr3.ndim
arr3.size
arr3.shape

1

3

(3,)

2

6

(2, 3)

3

6

(2, 3, 1)

In [63]:
# Get sample from standard normal distribution
# Mean = 0, Standard deviation = 1

np.random.randn()
np.random.randn(5)
np.random.randn(5, 2)

-0.6871727001195994

array([-0.8452, -0.6712, -0.0127, -1.1173,  0.2344])

array([[ 1.6598,  0.742 ],
       [-0.1918, -0.8876],
       [-0.7472,  1.6925],
       [ 0.0508, -0.637 ],
       [ 0.1909,  2.1003]])

In [16]:
np.random.randint(6)
np.random.randint(6, 9)
np.random.randint(6, 9, 3)
np.random.randint(6, 9, (2, 3))
np.random.randint(6, 9, (2, 3, 1))

0

6

array([8, 6, 8], dtype=int32)

array([[7, 8, 7],
       [8, 6, 8]], dtype=int32)

array([[[6],
        [8],
        [6]],

       [[8],
        [7],
        [6]]], dtype=int32)

In [17]:
np.linspace(2, 3, 5)  # 5 Numbers evenly spaced between two and three
np.linspace(1, 3, 3)
np.linspace(1, 3, 6)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

array([1., 2., 3.])

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [18]:
# Continuous integers start and stop index
np.arange(5)
np.arange(2, 6)
np.arange(70, 80)

array([0, 1, 2, 3, 4])

array([2, 3, 4, 5])

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79])

In [64]:
# Get the matrix of the shape from an existing matrix

arr = np.zeros(10)
arr.shape
arr.reshape(2, 5).shape
arr.reshape(5, 2).shape
arr.reshape(5, 2, 1).shape
arr.reshape(5, 2, 1, 1).shape

(10,)

(2, 5)

(5, 2)

(5, 2, 1)

(5, 2, 1, 1)

In [20]:
arr = np.ones((2, 8))
arr.shape
arr.reshape(16)
arr.reshape(4, 4)
arr.reshape(2, 2, 4)

(2, 8)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
# Scalar elements -> singleton arr
arr = np.array([4, 5, 6])
arr.shape
np.expand_dims(arr, 1)
np.expand_dims(arr, 1).shape

(3,)

array([[4],
       [5],
       [6]])

(3, 1)

In [ ]:
# Singleton arr -> scalar elements
arr = np.array([[2], [3], [4]])
arr
arr.shape
np.squeeze(arr)
np.squeeze(arr).shape

array([[2],
       [3],
       [4]])

(3, 1)

array([2, 3, 4])

(3,)

In [23]:
matrix = np.array([[2, 3, 0],
                   [2, 3, 4]])

matrix.shape
matrix.T  # transpose
matrix.T.shape

(2, 3)

array([[2, 2],
       [3, 3],
       [0, 4]])

(3, 2)

In [24]:
np.hstack((
    np.array([9, 3, 6]),
    np.array([2, 4, 6]),
))

np.vstack((
    np.array([9, 3, 6]),
    np.array([2, 4, 6]),
))

array([9, 3, 6, 2, 4, 6])

array([[9, 3, 6],
       [2, 4, 6]])

In [25]:
np.stack((
    np.array([9, 3, 6]),
    np.array([2, 4, 6]),
), axis=0)

np.stack((
    np.array([9, 3, 6]),
    np.array([2, 4, 6]),
), axis=1)

array([[9, 3, 6],
       [2, 4, 6]])

array([[9, 2],
       [3, 4],
       [6, 6]])

In [26]:
np.concatenate((
    np.array([9, 3, 6]),
    np.array([2, 4, 6]),
), axis=0)

array([9, 3, 6, 2, 4, 6])

In [27]:
np.concatenate((
    np.array([[9, 3], [8, 3]]),
    np.array([[2, 4], [1, 3]]),
), axis=0)

np.concatenate((
    np.array([[9, 3], [8, 3]]),
    np.array([[2, 4], [1, 3]]),
), axis=1)

array([[9, 3],
       [8, 3],
       [2, 4],
       [1, 3]])

array([[9, 3, 2, 4],
       [8, 3, 1, 3]])

In [28]:
np.arange(10).sum()
np.arange(10).min()
np.arange(10).max()
np.arange(10).mean()
np.arange(10).var()
np.arange(10).std()

np.int64(45)

np.int64(0)

np.int64(9)

np.float64(4.5)

np.float64(8.25)

np.float64(2.8722813232690143)

In [66]:
arr = np.array([
    [1, 2, 3, 4],
    [6, 7, 8, 9],
    [9, 8, 7, 5]
])

arr.sum()
arr.sum(axis=0)
arr.sum(axis=1)

np.int64(69)

array([16, 17, 18, 18])

array([10, 30, 29])

In [67]:
# Broadcasting
arr1 = np.array([2, 3, 4])
arr2 = np.array([2, 4, 5])

arr1 + arr2
arr1 - arr2
arr1 // arr2
arr1 / arr2
arr1 * arr2

array([4, 7, 9])

array([ 0, -1, -1])

array([1, 0, 0])

array([1.  , 0.75, 0.8 ])

array([ 4, 12, 20])

In [31]:
np.array([2, 4, 5]) + 10
np.array([2, 4, 5]) - 10
np.array([2, 4, 5]) * 10
np.array([2, 4, 5]) / 10
np.array([2, 4, 5]) % 2

array([12, 14, 15])

array([-8, -6, -5])

array([20, 40, 50])

array([0.2, 0.4, 0.5])

array([0, 0, 1])

In [32]:
arr = np.array([[2, 4],
                [1, 3]])

arr + np.array([2, 4])

array([[4, 8],
       [3, 7]])

In [71]:
arr = np.array([5, 10, 15, 23, 6])
(arr % 5 == 0)  # bool mask
(arr % 5 == 0).sum()  # How many true values

array([ True,  True,  True, False, False])

np.int64(3)

In [34]:
# fancy indexing
arr = np.array([5, 10, 15, 23, 6])
arr[0]  # 0th element of arr
arr[[0, 1]]  # 0th 1st element of arr

np.int64(5)

array([ 5, 10])

In [35]:
# boolean mask
arr = np.array([5, 10, 15, 23, 6])

arr[[False, True, True, False, False]]
arr[arr % 5 == 0]
arr[(arr % 5 == 0) & (arr >= 10)]

array([10, 15])

array([ 5, 10, 15])

array([10, 15])

In [36]:
np.where(arr >= 10)  # indices where the condition is true
np.where(arr >= 10, 1, 0)

(array([1, 2, 3]),)

array([0, 1, 1, 1, 0])

In [37]:
arr = np.array([5, 10, 15, 23, 6])
arr.max()
arr.argmax()  # Index of the maximum

np.int64(23)

np.int64(3)

## The Normalizer

In [38]:
np.random.seed(1)
data = np.random.randint(0, 100, (10, 4))
data

array([[37, 12, 72,  9],
       [75,  5, 79, 64],
       [16,  1, 76, 71],
       [ 6, 25, 50, 20],
       [18, 84, 11, 28],
       [29, 14, 50, 68],
       [87, 87, 94, 96],
       [86, 13,  9,  7],
       [63, 61, 22, 57],
       [ 1,  0, 60, 81]], dtype=int32)

In [39]:
_min = data.min(axis=0)
_max = data.max(axis=0)
(data - _min) / (_max - _min)

array([[0.4186, 0.1379, 0.7412, 0.0225],
       [0.8605, 0.0575, 0.8235, 0.6404],
       [0.1744, 0.0115, 0.7882, 0.7191],
       [0.0581, 0.2874, 0.4824, 0.1461],
       [0.1977, 0.9655, 0.0235, 0.236 ],
       [0.3256, 0.1609, 0.4824, 0.6854],
       [1.    , 1.    , 1.    , 1.    ],
       [0.9884, 0.1494, 0.    , 0.    ],
       [0.7209, 0.7011, 0.1529, 0.5618],
       [0.    , 0.    , 0.6   , 0.8315]])

In [40]:
data = np.array([[37, 12, 72,  9],
                [75,  5, 79, 64],
                [1,  0, 60, 81]])

_min = data.min(axis=0)
_max = data.max(axis=0)

transformed_data = (data - _min) / (_max - _min)
transformed_data

array([[0.4865, 1.    , 0.6316, 0.    ],
       [1.    , 0.4167, 1.    , 0.7639],
       [0.    , 0.    , 0.    , 1.    ]])

## The "Borders" Logic

In [41]:
board = np.zeros((10, 10))
board[0::9] = 1
board[:, 0::9] = 1
board[2::2, 2::2] = 2
board[1::2, 1::2] = 2
board[4:6, 4:6] = 9
board

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 2., 0., 2., 0., 2., 0., 2., 0., 2.],
       [1., 0., 2., 0., 2., 0., 2., 0., 2., 1.],
       [1., 2., 0., 2., 0., 2., 0., 2., 0., 2.],
       [1., 0., 2., 0., 9., 9., 2., 0., 2., 1.],
       [1., 2., 0., 2., 9., 9., 0., 2., 0., 2.],
       [1., 0., 2., 0., 2., 0., 2., 0., 2., 1.],
       [1., 2., 0., 2., 0., 2., 0., 2., 0., 2.],
       [1., 0., 2., 0., 2., 0., 2., 0., 2., 1.],
       [1., 2., 1., 2., 1., 2., 1., 2., 1., 2.]])

In [42]:
data = np.array([
    [37, 12, 72,  9],
    [75,  5, 4, 64],
    [75,  1, 2, 5],
    [1,  0, 60, 81]
])
data[1:3, 1:-1]

array([[5, 4],
       [1, 2]])

In [43]:
data[0]
data[0, 0]
data[:, :-1]
data[0::2, :]
data[:, 0::3]

array([37, 12, 72,  9])

np.int64(37)

array([[37, 12, 72],
       [75,  5,  4],
       [75,  1,  2],
       [ 1,  0, 60]])

array([[37, 12, 72,  9],
       [75,  1,  2,  5]])

array([[37,  9],
       [75, 64],
       [75,  5],
       [ 1, 81]])

## The Outlier Finder

In [44]:
np.random.seed(1)

data = np.random.randn(100)

# Mean before replacement
data.mean()

twice_std = 2 * data.std()
dist = np.abs(data - data.mean())
mask = dist > twice_std
data[mask] = 99.9

# Mean after replacement
data.mean()

np.float64(0.060582852075698704)

np.float64(5.076563352867598)

In [45]:
data = np.array([2, 3, 4, 5])
data.mean()
data.std()

mask = np.abs(data - data.mean()) < data.std()
data[mask]

np.float64(3.5)

np.float64(1.118033988749895)

array([3, 4])

## Image-Style Manipulations (Channel Swapping)

In [46]:
np.random.seed(1)
data = np.random.randint(0, 256, (10, 10, 3))

data[:, :, 1] = 0  # "Mute" the Green channel
data.mean()  # brightness

red = data[:, :, 0]
blue = data[:, :, 2]
mask = (red > 200) & (blue < 50)
mask.sum()

np.float64(82.68333333333334)

np.int64(5)

In [47]:
np.random.seed(1)

data = np.random.randint(0, 10, (2, 2, 3))
data[:, :, 1] = 0  # "Mute" the Green channel
data
data[:, :, 0] > 5  # red channel
data[:, :, 2] > 5  # blue channel

data.mean()  # brightness

array([[[5, 0, 9],
        [5, 0, 0]],

       [[1, 0, 6],
        [9, 0, 4]]], dtype=int32)

array([[False, False],
       [False,  True]])

array([[ True, False],
       [ True, False]])

np.float64(3.25)

## The "Close Neighbors" Search

In [53]:
points = np.random.random((10, 2))
points
origin = np.array([0, 0])
origin

array([[0.0983, 0.4211],
       [0.9579, 0.5332],
       [0.6919, 0.3155],
       [0.6865, 0.8346],
       [0.0183, 0.7501],
       [0.9889, 0.7482],
       [0.2804, 0.7893],
       [0.1032, 0.4479],
       [0.9086, 0.2936],
       [0.2878, 0.13  ]])

array([0, 0])

In [57]:
np.sqrt(points[:, 0]**2 + points[:, 1]**2)

np.linalg.norm(points, axis=1)

array([0.4324, 1.0963, 0.7604, 1.0807, 0.7504, 1.24  , 0.8376, 0.4596,
       0.9549, 0.3158])

array([0.4324, 1.0963, 0.7604, 1.0807, 0.7504, 1.24  , 0.8376, 0.4596,
       0.9549, 0.3158])

In [59]:
min_idx = np.argmin(np.linalg.norm(points, axis=1))

points[min_idx]

array([0.2878, 0.13  ])